//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISPKlijenti_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstaliranaOprema
    {
        public int Id { get; set; }
        public int KlijentId { get; set; }
        public int OpremaMaterijalId { get; set; }
        public Nullable<int> Kolicina { get; set; }
        public byte[] Slika { get; set; }
    
        public virtual Klijenti Klijenti { get; set; }
        public virtual OpremaMaterijal OpremaMaterijal { get; set; }
    }
}
