//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISPKlijenti_API.Models
{
    using System;
    
    public partial class isp_Ugovori_Index
    {
        public int Id { get; set; }
        public int BrojUgovora { get; set; }
        public System.DateTime DatumPotpisivanja { get; set; }
        public string Usluga { get; set; }
        public string Klijent { get; set; }
    }
}
