//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISPKlijenti_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IspKlijentiEntities : DbContext
    {
        public IspKlijentiEntities()
            : base("name=IspKlijentiEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dobavljaci> Dobavljaci { get; set; }
        public virtual DbSet<InstaliranaOprema> InstaliranaOprema { get; set; }
        public virtual DbSet<Klijenti> Klijenti { get; set; }
        public virtual DbSet<MjerneJedinice> MjerneJedinice { get; set; }
        public virtual DbSet<Nabavka> Nabavka { get; set; }
        public virtual DbSet<OpremaMaterijal> OpremaMaterijal { get; set; }
        public virtual DbSet<RadniNalozi> RadniNalozi { get; set; }
        public virtual DbSet<Skladiste> Skladiste { get; set; }
        public virtual DbSet<StatusiNaloga> StatusiNaloga { get; set; }
        public virtual DbSet<Ugovori> Ugovori { get; set; }
        public virtual DbSet<Uloge> Uloge { get; set; }
        public virtual DbSet<Uplate> Uplate { get; set; }
        public virtual DbSet<Usluge> Usluge { get; set; }
        public virtual DbSet<Zaposlenici> Zaposlenici { get; set; }
        public virtual DbSet<ZaposleniciUloge> ZaposleniciUloge { get; set; }
        public virtual DbSet<KlijentiLog> KlijentiLog { get; set; }
        public virtual DbSet<Mjeseci> Mjeseci { get; set; }
        public virtual DbSet<Racuni> Racuni { get; set; }
        public virtual DbSet<NaciniPlacanja> NaciniPlacanja { get; set; }
        public virtual DbSet<PosebniRacuni> PosebniRacuni { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> isp_Klijenti_Insert(string ime, string prezime, string korisnickoIme, string email, string adresa, string telefon, Nullable<bool> aktivan)
        {
            var imeParameter = ime != null ?
                new ObjectParameter("Ime", ime) :
                new ObjectParameter("Ime", typeof(string));
    
            var prezimeParameter = prezime != null ?
                new ObjectParameter("Prezime", prezime) :
                new ObjectParameter("Prezime", typeof(string));
    
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var adresaParameter = adresa != null ?
                new ObjectParameter("Adresa", adresa) :
                new ObjectParameter("Adresa", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var aktivanParameter = aktivan.HasValue ?
                new ObjectParameter("Aktivan", aktivan) :
                new ObjectParameter("Aktivan", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("isp_Klijenti_Insert", imeParameter, prezimeParameter, korisnickoImeParameter, emailParameter, adresaParameter, telefonParameter, aktivanParameter);
        }
    
        public virtual ObjectResult<Klijenti> isp_Klijenti_SelectByImePrezime(string imePrezime)
        {
            var imePrezimeParameter = imePrezime != null ?
                new ObjectParameter("ImePrezime", imePrezime) :
                new ObjectParameter("ImePrezime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Klijenti>("isp_Klijenti_SelectByImePrezime", imePrezimeParameter);
        }
    
        public virtual ObjectResult<Klijenti> isp_Klijenti_SelectByImePrezime(string imePrezime, MergeOption mergeOption)
        {
            var imePrezimeParameter = imePrezime != null ?
                new ObjectParameter("ImePrezime", imePrezime) :
                new ObjectParameter("ImePrezime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Klijenti>("isp_Klijenti_SelectByImePrezime", mergeOption, imePrezimeParameter);
        }
    
        public virtual ObjectResult<Zaposlenici> isp_Zaposlenici_SelectByImePrezime(string imePrezime)
        {
            var imePrezimeParameter = imePrezime != null ?
                new ObjectParameter("ImePrezime", imePrezime) :
                new ObjectParameter("ImePrezime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zaposlenici>("isp_Zaposlenici_SelectByImePrezime", imePrezimeParameter);
        }
    
        public virtual ObjectResult<Zaposlenici> isp_Zaposlenici_SelectByImePrezime(string imePrezime, MergeOption mergeOption)
        {
            var imePrezimeParameter = imePrezime != null ?
                new ObjectParameter("ImePrezime", imePrezime) :
                new ObjectParameter("ImePrezime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zaposlenici>("isp_Zaposlenici_SelectByImePrezime", mergeOption, imePrezimeParameter);
        }
    
        public virtual ObjectResult<isp_Ugovori_Index> isp_Ugovori_SelectByKlijent(string imePrezime)
        {
            var imePrezimeParameter = imePrezime != null ?
                new ObjectParameter("ImePrezime", imePrezime) :
                new ObjectParameter("ImePrezime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<isp_Ugovori_Index>("isp_Ugovori_SelectByKlijent", imePrezimeParameter);
        }
    
        public virtual ObjectResult<isp_Ugovori_Index> isp_Ugovori_SelectByBrojUgovora(Nullable<int> brojUgovora)
        {
            var brojUgovoraParameter = brojUgovora.HasValue ?
                new ObjectParameter("BrojUgovora", brojUgovora) :
                new ObjectParameter("BrojUgovora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<isp_Ugovori_Index>("isp_Ugovori_SelectByBrojUgovora", brojUgovoraParameter);
        }
    
        public virtual ObjectResult<isp_RadniNalozi_SelectByKlijent_Result> isp_RadniNalozi_Index(string klijent)
        {
            var klijentParameter = klijent != null ?
                new ObjectParameter("Klijent", klijent) :
                new ObjectParameter("Klijent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<isp_RadniNalozi_SelectByKlijent_Result>("isp_RadniNalozi_Index", klijentParameter);
        }
    
        public virtual ObjectResult<isp_Dobavljaci_SelectByNaziv_Result> isp_Dobavljaci_SelectByNaziv(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<isp_Dobavljaci_SelectByNaziv_Result>("isp_Dobavljaci_SelectByNaziv", nazivParameter);
        }
    
        public virtual ObjectResult<isp_Oprema_SelectAll_Result> isp_Oprema_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<isp_Oprema_SelectAll_Result>("isp_Oprema_SelectAll");
        }
    
        public virtual ObjectResult<isp_Skladiste_SelectAll_Result> isp_Skladiste_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<isp_Skladiste_SelectAll_Result>("isp_Skladiste_SelectAll");
        }
    
        public virtual ObjectResult<isp_Nabavka_SelectById_Result> isp_Nabavka_SelectById(Nullable<int> nabavkaId)
        {
            var nabavkaIdParameter = nabavkaId.HasValue ?
                new ObjectParameter("NabavkaId", nabavkaId) :
                new ObjectParameter("NabavkaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<isp_Nabavka_SelectById_Result>("isp_Nabavka_SelectById", nabavkaIdParameter);
        }
    
        public virtual ObjectResult<isp_Nabavka_SelectByDatum_Result> isp_Nabavka_SelectByDatum(Nullable<System.DateTime> datum1, Nullable<System.DateTime> datum2)
        {
            var datum1Parameter = datum1.HasValue ?
                new ObjectParameter("datum1", datum1) :
                new ObjectParameter("datum1", typeof(System.DateTime));
    
            var datum2Parameter = datum2.HasValue ?
                new ObjectParameter("datum2", datum2) :
                new ObjectParameter("datum2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<isp_Nabavka_SelectByDatum_Result>("isp_Nabavka_SelectByDatum", datum1Parameter, datum2Parameter);
        }
    
        public virtual ObjectResult<Skladiste> isp_Skladiste_SelectByOprema(Nullable<int> opremaId)
        {
            var opremaIdParameter = opremaId.HasValue ?
                new ObjectParameter("OpremaId", opremaId) :
                new ObjectParameter("OpremaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Skladiste>("isp_Skladiste_SelectByOprema", opremaIdParameter);
        }
    
        public virtual ObjectResult<Skladiste> isp_Skladiste_SelectByOprema(Nullable<int> opremaId, MergeOption mergeOption)
        {
            var opremaIdParameter = opremaId.HasValue ?
                new ObjectParameter("OpremaId", opremaId) :
                new ObjectParameter("OpremaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Skladiste>("isp_Skladiste_SelectByOprema", mergeOption, opremaIdParameter);
        }
    
        public virtual ObjectResult<isp_Racuni_SelectByKlijent_Result> isp_Racuni_SelectByKlijent(string imePrezime)
        {
            var imePrezimeParameter = imePrezime != null ?
                new ObjectParameter("ImePrezime", imePrezime) :
                new ObjectParameter("ImePrezime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<isp_Racuni_SelectByKlijent_Result>("isp_Racuni_SelectByKlijent", imePrezimeParameter);
        }
    
        public virtual ObjectResult<isp_Racuni_SelectById_Result> isp_Racuni_SelectById(Nullable<int> racunId)
        {
            var racunIdParameter = racunId.HasValue ?
                new ObjectParameter("RacunId", racunId) :
                new ObjectParameter("RacunId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<isp_Racuni_SelectById_Result>("isp_Racuni_SelectById", racunIdParameter);
        }
    
        public virtual ObjectResult<isp_InstaliranaOprema_SelectyByKlijent_Result> isp_InstaliranaOprema_SelectyByKlijent(string klijent)
        {
            var klijentParameter = klijent != null ?
                new ObjectParameter("Klijent", klijent) :
                new ObjectParameter("Klijent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<isp_InstaliranaOprema_SelectyByKlijent_Result>("isp_InstaliranaOprema_SelectyByKlijent", klijentParameter);
        }
    
        public virtual ObjectResult<isp_PosebniRacuni_SelectAll_Result> isp_PosebniRacuni_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<isp_PosebniRacuni_SelectAll_Result>("isp_PosebniRacuni_SelectAll");
        }
    
        public virtual ObjectResult<isp_PosebniRacuni_SelectById_Result> isp_PosebniRacuni_SelectById(Nullable<int> posebniRacunId)
        {
            var posebniRacunIdParameter = posebniRacunId.HasValue ?
                new ObjectParameter("PosebniRacunId", posebniRacunId) :
                new ObjectParameter("PosebniRacunId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<isp_PosebniRacuni_SelectById_Result>("isp_PosebniRacuni_SelectById", posebniRacunIdParameter);
        }
    }
}
