//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISPKlijenti_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racuni
    {
        public int Id { get; set; }
        public int KlijentId { get; set; }
        public int UslugaId { get; set; }
        public int Kolicina { get; set; }
        public decimal IznosBezPDV { get; set; }
        public decimal IznosSaPDV { get; set; }
        public int MjesecId { get; set; }
        public System.DateTime VrijemeIsporuke { get; set; }
        public bool Placeno { get; set; }
        public int NacinPlacanjaId { get; set; }
    
        public virtual Klijenti Klijenti { get; set; }
        public virtual Mjeseci Mjeseci { get; set; }
        public virtual Usluge Usluge { get; set; }
        public virtual NaciniPlacanja NaciniPlacanja { get; set; }
    }
}
