//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISPKlijenti_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ugovori
    {
        public int Id { get; set; }
        public int BrojUgovora { get; set; }
        public System.DateTime DatumPotpisivanja { get; set; }
        public int UslugaId { get; set; }
        public int KlijentId { get; set; }
    
        public virtual Klijenti Klijenti { get; set; }
        public virtual Usluge Usluge { get; set; }
    }
}
