//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISPKlijenti_UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISPKlijenti_UI.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravan unos..
        /// </summary>
        internal static string adresa_rgx {
            get {
                return ResourceManager.GetString("adresa_rgx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je obavezno polje..
        /// </summary>
        internal static string email_req {
            get {
                return ResourceManager.GetString("email_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravan format maila..
        /// </summary>
        internal static string email_rgx {
            get {
                return ResourceManager.GetString("email_rgx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime mora biti duže od jednog karaktera!.
        /// </summary>
        internal static string ime_len {
            get {
                return ResourceManager.GetString("ime_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime je obavezno polje!.
        /// </summary>
        internal static string ime_req {
            get {
                return ResourceManager.GetString("ime_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ne može biti kraće od 5 znakova!.
        /// </summary>
        internal static string korIme_len {
            get {
                return ResourceManager.GetString("korIme_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je obavezno polje!.
        /// </summary>
        internal static string korIme_req {
            get {
                return ResourceManager.GetString("korIme_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime može sadržavati brojeve, velika i mala slova, bez razmaka..
        /// </summary>
        internal static string korIme_rgx {
            get {
                return ResourceManager.GetString("korIme_rgx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka ne može biti kraća od 5 karaktera..
        /// </summary>
        internal static string lozinka_len {
            get {
                return ResourceManager.GetString("lozinka_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka je obavezno polje..
        /// </summary>
        internal static string lozinka_req {
            get {
                return ResourceManager.GetString("lozinka_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dozvoljen unos samo slova, brojeva i #$ znakova..
        /// </summary>
        internal static string lozinka_rgx {
            get {
                return ResourceManager.GetString("lozinka_rgx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime mora biti duže od jednog karaktera!.
        /// </summary>
        internal static string prezime_len {
            get {
                return ResourceManager.GetString("prezime_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime je obavezno polje!.
        /// </summary>
        internal static string prezime_req {
            get {
                return ResourceManager.GetString("prezime_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon je obavezno polje!.
        /// </summary>
        internal static string telefon_req {
            get {
                return ResourceManager.GetString("telefon_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odabrati bar 1 ulogu..
        /// </summary>
        internal static string uloga_req {
            get {
                return ResourceManager.GetString("uloga_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno izabrati uslugu za klijenta!.
        /// </summary>
        internal static string usluge_req {
            get {
                return ResourceManager.GetString("usluge_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unijeli ste nedozvoljene znakove!.
        /// </summary>
        internal static string wrong_rgx {
            get {
                return ResourceManager.GetString("wrong_rgx", resourceCulture);
            }
        }
    }
}
